"""empty message

Revision ID: 0dc1b5770f61
Revises: e38a9513fe46
Create Date: 2020-05-25 21:46:12.375013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc1b5770f61'
down_revision = 'e38a9513fe46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
