"""empty message

Revision ID: 12fe63dbc6a1
Revises: 32346bd4a8f8
Create Date: 2020-05-25 19:20:02.847062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fe63dbc6a1'
down_revision = '32346bd4a8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
