"""empty message

Revision ID: 61732c9e74e9
Revises: dc201418b108
Create Date: 2020-05-23 10:56:45.482590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61732c9e74e9'
down_revision = 'dc201418b108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
