"""empty message

Revision ID: 8444b72497b8
Revises: 61732c9e74e9
Create Date: 2020-05-23 10:59:00.722869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8444b72497b8'
down_revision = '61732c9e74e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
