"""empty message

Revision ID: e38a9513fe46
Revises: c5c3a3ab09ad
Create Date: 2020-05-25 21:43:04.094150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38a9513fe46'
down_revision = 'c5c3a3ab09ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
